const PRODUCTS = [
  // Салати
  { id: "salad-horiatiki", name: "Гръцка салата Хориатики", category: "Салати", categorySlug: "salads", price: 9.90, unit: "450г", img: "https://images.unsplash.com/photo-1623428187969-5da2d87e0afb?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Домати, краставици, лук, маслини и фета сирене.",
    longDesc: "Класическата гръцка хориатики — сочни домати, хрупкави краставици, червен лук и каламата маслини, увенчани с дебело парче фета сирене и щедра доза зехтин. Проста, свежа и вярна на автентичната рецепта." },
  { id: "salad-calamari", name: "Салата с калмари на скара", category: "Салати", categorySlug: "salads", price: 12.50, unit: "300г", img: "https://images.unsplash.com/photo-1534080391025-a77c7ecb1e5a?auto=format&fit=crop&w=600&q=80",
    desc: "Салатен микс от листни зеленчуци с калмари на скара и лимонов дресинг.",
    longDesc: "Свеж листен микс, увенчан с крехки калмари, приготвени на скара до перфектност, и лек лимонов дресинг с зехтин. Лека, но засищаща опция за истински ценители на морето." },
  { id: "salad-dakos", name: "Критски дакос", category: "Салати", categorySlug: "salads", price: 8.50, unit: "350г", img: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=600&q=80",
    desc: "Сухар с домати, мека фета мицитра и риган.",
    longDesc: "Традиционен критски дакос — навлажнен ечемичен сухар, покрит с настърган узрял домат, мека сирена мицитра, зехтин и щипка риган. Автентичен вкус на остров Крит." },
  { id: "salad-octopus", name: "Салата с октопод и рукола", category: "Салати", categorySlug: "salads", price: 14.90, unit: "320г", img: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    desc: "Крехък октопод върху свежа рукола с чери домати.",
    longDesc: "Нежно сварен и леко запечен октопод върху легло от свежа рукола и сладки чери домати, с дресинг от зехтин и балсамов оцет. Елегантно предястие с морски характер." },
  { id: "salad-politiki", name: "Политики салата (зелева)", category: "Салати", categorySlug: "salads", price: 7.50, unit: "400г", img: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80",
    desc: "Финно нарязано зеле, моркови и билков дресинг.",
    longDesc: "Хрупкава зелева салата по цариградски рецепти — финно нарязано бяло зеле и моркови, овкусени с лек билков дресинг. Идеалният свеж партньор на всяка скара." },
  { id: "salad-peppers-feta", name: "Печени чушки и фета", category: "Салати", categorySlug: "salads", price: 8.90, unit: "350г", img: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=600&q=80",
    desc: "Сладки печени чушки с маслини и фета сирене.",
    longDesc: "Печени на жар сладки чушки, обелени и подправени със зехтин, чесън и билки, поднесени с маслини и парчета фета. Наситен, димен вкус в комбинация с кремообразно сирене." },
  { id: "meze-platter", name: "Гръцко meze плато", category: "Салати", categorySlug: "salads", price: 13.90, unit: "за споделяне", img: "https://images.unsplash.com/photo-1541014741259-df549fa9ba6f?auto=format&fit=crop&w=600&q=80",
    desc: "Дзадзики, хумус, маслини, питка и зеленчуци.",
    longDesc: "Богато плато за споделяне — домашно приготвени дзадзики и хумус, каламата маслини, топла питка, долмадес и свежи зеленчуци. Перфектно начало за всяка гръцка трапеза." },

  // Рибни ястия
  { id: "fish-brancho", name: "Цял морски бран на скара", category: "Рибни ястия", categorySlug: "fish", price: 16.90, unit: "1 бр.", img: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Прясна риба на скара с лимон, зехтин и билки.",
    longDesc: "Цял морски бран, приготвен на скара до златиста коричка, поднесен с прясно изцеден лимон, зехтин първо студено пресоване и свежи средиземноморски билки. Просто и невероятно вкусно." },
  { id: "fish-lavrak", name: "Филе от лаврак", category: "Рибни ястия", categorySlug: "fish", price: 15.50, unit: "300г", img: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
    desc: "Нежно филе с лимон, чесън и свежи билки.",
    longDesc: "Нежно филе от лаврак, леко мариновано в зехтин, чесън, лимон и билки, след което приготвено на скара. Фина текстура и деликатен вкус на морето." },
  { id: "fish-calamari", name: "Калмари на скара", category: "Рибни ястия", categorySlug: "fish", price: 13.90, unit: "300г", img: "https://images.unsplash.com/photo-1534080391025-a77c7ecb1e5a?auto=format&fit=crop&w=600&q=80",
    desc: "Крехки калмари, приготвени на скара с лимон.",
    longDesc: "Свежи калмари на скара, овкусени единствено с зехтин, лимон и риган, за да изпъкне естественият им вкус. Крехки, сочни и готови за секунди." },
  { id: "fish-shrimp-saganaki", name: "Скариди Сарагано", category: "Рибни ястия", categorySlug: "fish", price: 17.90, unit: "250г", img: "https://images.unsplash.com/photo-1559737605-de6a7ceb6a9a?auto=format&fit=crop&w=600&q=80",
    desc: "Скариди в сос с домати, фета и узо.",
    longDesc: "Сочни скариди, задушени в наситен сос от домати, чесън и капка узо, завършени с разтопена фета сирене. Ястие с характер, поднасяно директно в тавичка." },
  { id: "octopus-grill", name: "Октопод на скара", category: "Рибни ястия", categorySlug: "fish", price: 19.90, unit: "300г", img: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    desc: "Крехък октопод с олио, оцет и риган.",
    longDesc: "Дълго и внимателно приготвен октопод, запечен на скара до крехкост, поднесен с зехтин, оцет и риган — по класическата гръцка таверна рецепта." },
  { id: "fish-sardines", name: "Сардини на скара", category: "Рибни ястия", categorySlug: "fish", price: 9.90, unit: "300г", img: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=600&q=80",
    desc: "Прясно уловени сардини, на скара с лимон.",
    longDesc: "Дребни прясно уловени сардини, набързо изпечени на скара и поднесени с лимон и зехтин. Просто крайбрежно ястие с наситен вкус." },

  // Пилешки шишове
  { id: "chicken-souvlaki", name: "Пилешко сувлаки", category: "Пилешки шишове", categorySlug: "chicken", price: 8.90, unit: "2 бр.", img: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Класическо гръцко сувлаки, маринован и на скара.",
    longDesc: "Сочни парчета пилешко бутче, мариновани в зехтин, лимон, чесън и риган, набодени на шишче и препечени на скара до златисто. Класика на гръцката улична кухня." },
  { id: "chicken-peppers", name: "Пилешки шиш с чушки и лук", category: "Пилешки шишове", categorySlug: "chicken", price: 6.90, unit: "1 бр.", img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80",
    desc: "Сочно пиле с чушки и лук на дървени шишчета.",
    longDesc: "Хапки пилешко месо, редувани с чушки и лук на дървено шишче, овкусени с гръцки подправки и препечени на скара. Ярко и ароматно ястие за всеки повод." },
  { id: "chicken-honey-mustard", name: "Сувлаки медено-горчично", category: "Пилешки шишове", categorySlug: "chicken", price: 9.90, unit: "2 бр.", img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80",
    desc: "Пилешко сувлаки с лека сладко-пикантна глазура.",
    longDesc: "Нашата класическа пилешка сувлаки, гарнирана с лека медено-горчична глазура за нотка сладост и пикантност. Балансиран, съвременен привкус върху традиционна основа." },
  { id: "chicken-kebap", name: "Пилешки кебап на скара", category: "Пилешки шишове", categorySlug: "chicken", price: 10.90, unit: "300г", img: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80",
    desc: "Кайма от пилешко месо с подправки, на скара.",
    longDesc: "Ръчно оформена кайма от пилешко месо, подправена с чесън, магданоз и подправки по гръцки, изпечена на скара до сочност. Богат вкус, лека текстура." },

  // Свински шишове
  { id: "pork-souvlaki", name: "Свинско сувлаки", category: "Свински шишове", categorySlug: "pork", price: 8.50, unit: "2 бр.", img: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Сочно свинско на скара по традиционна рецепта.",
    longDesc: "Кубчета свинско месо, мариновани в зехтин, лимон и риган, приготвени на шишче над жар до сочна, леко карамелизирана коричка. Вечна класика на гръцката трапеза." },
  { id: "pork-gyros", name: "Свински шиш „Гирос“", category: "Свински шишове", categorySlug: "pork", price: 9.50, unit: "2 бр.", img: "https://images.unsplash.com/photo-1524351199679-46cddf530c04?auto=format&fit=crop&w=600&q=80",
    desc: "Ароматни подправки в гръцки гирос стил.",
    longDesc: "Сочно свинско месо, мариновано с наситена смес от гирос подправки, приготвено на скара до крехкост. Идеално за поднасяне с питка и дзадзики." },
  { id: "pork-kebap", name: "Свински кебап на скара", category: "Свински шишове", categorySlug: "pork", price: 10.50, unit: "300г", img: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80",
    desc: "Сочна кайма от свинско, подправена по гръцки.",
    longDesc: "Ръчно оформена кайма от свинско месо с чесън, риган и подправки, изпечена на скара до сочна коричка. Богат, наситен вкус за истинските любители на скарата." },
  { id: "pork-combo", name: "Мешана скара свинско (комбо)", category: "Свински шишове", categorySlug: "pork", price: 13.90, unit: "400г", img: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80",
    desc: "Комбинация от свинско сувлаки, кебап и колбас.",
    longDesc: "Щедра комбинация от свинско сувлаки, кебап на скара и пикантен колбас — идеална за споделяне или за истински гладни моменти. Всичко на скара, всичко сочно." },

  // Алкохол
  { id: "ouzo-700", name: "Узо, 700мл", category: "Алкохол", categorySlug: "alcohol", price: 24.90, unit: "700мл", img: "https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Автентичен гръцки анасонов ликьор.",
    longDesc: "Традиционен гръцки анасонов дестилат с деликатен, ароматен профил. Поднесете със студена вода и лед за класическото гръцко преживяване с мезе." },
  { id: "wine-assyrtiko", name: "Асиртико — бяло вино", category: "Алкохол", categorySlug: "alcohol", price: 19.90, unit: "750мл", img: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80",
    desc: "Свежо санторинско бяло вино.",
    longDesc: "Сухо бяло вино от сорта Асиртико, отглеждан на вулканичните почви на Санторини. Свежа минералност и цитрусови нотки, перфектно за морски специалитети." },
  { id: "wine-agiorgitiko", name: "Агиоргитико — червено вино", category: "Алкохол", categorySlug: "alcohol", price: 21.90, unit: "750мл", img: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
    desc: "Плътно червено вино от лозята на Немея.",
    longDesc: "Плътно, кадифено червено вино от прочутия сорт Агиоргитико в района на Немея. Аромати на червени плодове и подправки, чудесно с червени меса." },
  { id: "beer-mythos", name: "Гръцка бира „Митос“", category: "Алкохол", categorySlug: "alcohol", price: 4.50, unit: "500мл", img: "https://images.unsplash.com/photo-1567696911980-2dea991db80b?auto=format&fit=crop&w=600&q=80",
    desc: "Лека и освежаваща светла бира.",
    longDesc: "Лека светла бира с хрупкав, освежаващ финал. Чудесен спътник на топло гръцко слънце и мезе с приятели." },
  { id: "metaxa-5", name: "Метакса 5*", category: "Алкохол", categorySlug: "alcohol", price: 26.90, unit: "700мл", img: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
    desc: "Изискан гръцки брандито с богат аромат.",
    longDesc: "Изискано гръцко бренди, отлежало в дъбови бъчви, с богат аромат на карамел и подправки. Насладете се чисто или с лед след вечеря." },
  { id: "rose-moschofilero", name: "Розе Москофилеро", category: "Алкохол", categorySlug: "alcohol", price: 20.90, unit: "750мл", img: "https://images.unsplash.com/photo-1553077189-2de686a778e2?auto=format&fit=crop&w=600&q=80",
    desc: "Ароматно розе с нотки на цитрус и рози.",
    longDesc: "Свежо розе от ароматния сорт Москофилеро, с деликатни нотки на цитрус и розов цвят. Лек и елегантен избор за топли вечери." },

  // Безалкохолни напитки
  { id: "lemonade-330", name: "Гръцка лимонада", category: "Безалкохолни напитки", categorySlug: "drinks", price: 3.20, unit: "330мл", img: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80", tag: "Хит",
    desc: "Освежаваща домашна лимонада с мента.",
    longDesc: "Домашно приготвена лимонада от прясно изцедени лимони и щипка свежа мента. Освежаваща и лека, перфектна за горещите летни дни." },
  { id: "water-sariza", name: "Минерална вода „Сариза“", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.20, unit: "500мл", img: "https://images.unsplash.com/photo-1608885898957-a599fb1b4670?auto=format&fit=crop&w=600&q=80",
    desc: "Прочута гръцка изворна минерална вода.",
    longDesc: "Естествена изворна минерална вода от планините на Гърция, с балансиран минерален състав и чист, свеж вкус." },
  { id: "frappe", name: "Гръцко фрапе", category: "Безалкохолни напитки", categorySlug: "drinks", price: 4.50, unit: "400мл", img: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=600&q=80",
    desc: "Студено разбито кафе с пяна, по гръцка традиция.",
    longDesc: "Културовата гръцка напитка — студено разбито кафе с гъста пяна, поднесено с лед. Освежаващо и бодрящо във всеки сезон." },
  { id: "ayran", name: "Айрян", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.90, unit: "330мл", img: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=600&q=80",
    desc: "Освежаваща напитка от кисело мляко.",
    longDesc: "Класическа освежаваща напитка от кисело мляко, вода и щипка сол. Лек и хидратиращ съпровод на всяко ястие на скара." },
  { id: "orange-juice", name: "Прясно изцеден портокалов сок", category: "Безалкохолни напитки", categorySlug: "drinks", price: 4.90, unit: "330мл", img: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=600&q=80",
    desc: "100% натурален сок от узрели портокали.",
    longDesc: "Прясно изцеден сок от узрели портокали, без добавена захар или консерванти. Чист вкус на слънце в чаша." },
  { id: "sparkling-water", name: "Газирана вода", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.50, unit: "330мл", img: "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?auto=format&fit=crop&w=600&q=80",
    desc: "Изворна газирана вода за освежаване.",
    longDesc: "Освежаваща изворна газирана вода с фини мехурчета. Чудесен, лек избор към всяко ястие от менюто." },
];радиционен гръцки анасонов дестилат с деликатен, ароматен профил. Поднесете със студена вода и лед за класическото гръцко преживяване с мезе." },
  { id: "wine-assyrtiko", name: "Асиртико — бяло вино", category: "Алкохол", categorySlug: "alcohol", price: 19.90, unit: "750мл", img: "images/illustrations/alcohol.svg",
    desc: "Свежо санторинско бяло вино.",
    longDesc: "Сухо бяло вино от сорта Асиртико, отглеждан на вулканичните почви на Санторини. Свежа минералност и цитрусови нотки, перфектно за морски специалитети." },
  { id: "wine-agiorgitiko", name: "Агиоргитико — червено вино", category: "Алкохол", categorySlug: "alcohol", price: 21.90, unit: "750мл", img: "images/illustrations/alcohol.svg",
    desc: "Плътно червено вино от лозята на Немея.",
    longDesc: "Плътно, кадифено червено вино от прочутия сорт Агиоргитико в района на Немея. Аромати на червени плодове и подправки, чудесно с червени меса." },
  { id: "beer-mythos", name: "Гръцка бира „Митос“", category: "Алкохол", categorySlug: "alcohol", price: 4.50, unit: "500мл", img: "images/illustrations/alcohol.svg",
    desc: "Лека и освежаваща светла бира.",
    longDesc: "Лека светла бира с хрупкав, освежаващ финал. Чудесен спътник на топло гръцко слънце и мезе с приятели." },
  { id: "metaxa-5", name: "Метакса 5*", category: "Алкохол", categorySlug: "alcohol", price: 26.90, unit: "700мл", img: "images/illustrations/alcohol.svg",
    desc: "Изискан гръцки брандито с богат аромат.",
    longDesc: "Изискано гръцко бренди, отлежало в дъбови бъчви, с богат аромат на карамел и подправки. Насладете се чисто или с лед след вечеря." },
  { id: "rose-moschofilero", name: "Розе Москофилеро", category: "Алкохол", categorySlug: "alcohol", price: 20.90, unit: "750мл", img: "images/illustrations/alcohol.svg",
    desc: "Ароматно розе с нотки на цитрус и рози.",
    longDesc: "Свежо розе от ароматния сорт Москофилеро, с деликатни нотки на цитрус и розов цвят. Лек и елегантен избор за топли вечери." },

  // Безалкохолни напитки
  { id: "lemonade-330", name: "Гръцка лимонада", category: "Безалкохолни напитки", categorySlug: "drinks", price: 3.20, unit: "330мл", img: "images/illustrations/drinks.svg", tag: "Хит",
    desc: "Освежаваща домашна лимонада с мента.",
    longDesc: "Домашно приготвена лимонада от прясно изцедени лимони и щипка свежа мента. Освежаваща и лека, перфектна за горещите летни дни." },
  { id: "water-sariza", name: "Минерална вода „Сариза“", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.20, unit: "500мл", img: "images/illustrations/drinks.svg",
    desc: "Прочута гръцка изворна минерална вода.",
    longDesc: "Естествена изворна минерална вода от планините на Гърция, с балансиран минерален състав и чист, свеж вкус." },
  { id: "frappe", name: "Гръцко фрапе", category: "Безалкохолни напитки", categorySlug: "drinks", price: 4.50, unit: "400мл", img: "images/illustrations/drinks.svg",
    desc: "Студено разбито кафе с пяна, по гръцка традиция.",
    longDesc: "Културовата гръцка напитка — студено разбито кафе с гъста пяна, поднесено с лед. Освежаващо и бодрящо във всеки сезон." },
  { id: "ayran", name: "Айрян", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.90, unit: "330мл", img: "images/illustrations/drinks.svg",
    desc: "Освежаваща напитка от кисело мляко.",
    longDesc: "Класическа освежаваща напитка от кисело мляко, вода и щипка сол. Лек и хидратиращ съпровод на всяко ястие на скара." },
  { id: "orange-juice", name: "Прясно изцеден портокалов сок", category: "Безалкохолни напитки", categorySlug: "drinks", price: 4.90, unit: "330мл", img: "images/illustrations/drinks.svg",
    desc: "100% натурален сок от узрели портокали.",
    longDesc: "Прясно изцеден сок от узрели портокали, без добавена захар или консерванти. Чист вкус на слънце в чаша." },
  { id: "sparkling-water", name: "Газирана вода", category: "Безалкохолни напитки", categorySlug: "drinks", price: 2.50, unit: "330мл", img: "images/illustrations/drinks.svg",
    desc: "Изворна газирана вода за освежаване.",
    longDesc: "Освежаваща изворна газирана вода с фини мехурчета. Чудесен, лек избор към всяко ястие от менюто." },
];

function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

function getRelatedProducts(product, limit) {
  return PRODUCTS.filter(p => p.categorySlug === product.categorySlug && p.id !== product.id).slice(0, limit || 4);
}
